version: '3'
services:
  redis:
    image: redis/redis-stack-server:latest
    restart: always
    volumes:
      - ./data:/data
  talker:
    image: python:3.11
    command: sh -c "pip install -r requirements.txt && pip install waitress && python -m waitress api.index:app"
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 5000:8080
    environment:
      - KV_URL=redis://redis:6379/0
      - OPENAI_API_BASE=api.openai.com
      # Your OpenAI key here
      - OPENAI_API_KEY=<your-openai-kay>
